// Maps Google Places category strings to CallDeck industry labels.
// Keys are lowercase Google category slugs (from places API `types` field).
// Values match INDUSTRIES labels from prospect-categories.ts.

export const CATEGORY_TO_INDUSTRY: Record<string, string> = {
  // Direct matches to INDUSTRIES labels in prospect-categories.ts
  accountant: "Accountant",
  accounting: "Accountant",
  auto_repair: "Auto Repair",
  car_repair: "Auto Repair",
  car_dealer: "Auto Repair",
  chiropractor: "Chiropractor",
  cleaning_service: "Cleaning Services",
  dentist: "Dentist",
  electrician: "Electrician",
  gym: "Gym / Fitness",
  hair_care: "Hair Salon",
  hair_salon: "Hair Salon",
  beauty_salon: "Hair Salon",
  hvac: "HVAC",
  insurance_agency: "Insurance",
  finance: "Insurance",
  landscaping: "Landscaping",
  lawyer: "Lawyer",
  law_firm: "Lawyer",
  pest_control: "Pest Control",
  pet_grooming: "Pet Grooming",
  plumber: "Plumber",
  real_estate_agency: "Real Estate",
  restaurant: "Restaurant",
  bakery: "Restaurant",
  bar: "Restaurant",
  cafe: "Restaurant",
  meal_takeaway: "Restaurant",
  food: "Restaurant",
  roofing_contractor: "Roofing",
  general_contractor: "Construction",
  spa: "Spa / Wellness",
  health: "Healthcare",
  doctor: "Healthcare",
  hospital: "Healthcare",
  physiotherapist: "Healthcare",
  veterinary_care: "Veterinarian",
  pet_store: "Pet Grooming",

  // Additional categories found in current data
  church: "Religious Organization",
  place_of_worship: "Religious Organization",
  funeral_home: "Funeral Services",
  cemetery: "Funeral Services",
  school: "Education",
  secondary_school: "Education",
  university: "Education",
  library: "Education",
  clothing_store: "Retail",
  department_store: "Retail",
  electronics_store: "Retail",
  furniture_store: "Retail",
  hardware_store: "Retail",
  home_goods_store: "Retail",
  shoe_store: "Retail",
  shopping_mall: "Retail",
  store: "Retail",
  grocery_or_supermarket: "Retail",
  supermarket: "Retail",
  lodging: "Hospitality",
  movie_theater: "Entertainment",
  courthouse: "Government",
  local_government_office: "Government",
  police: "Government",
};
